### ISSUE TITLE
Search filter set every frame in editor

### ISSUE THREAD

**Issue by tivec** [linuxgurugamer/QuickMods#8] opened 2020-02-23 14:05 UTC
I've been looking at reasons why the search is so incredibly slow in the VAB, and stumbled on the refresh method in QuickSearch.
https://github.com/linuxgurugamer/QuickMods/blob/a615c20311cceab4ad4e889cde8cac92ae4cda06/QuickSearch/QS_Editor.cs#L175-L179

For some reason, the filter is set every frame. While this *probably* isn't the cause for the slowdown, it sure does not help. I'll dig a bit at this and set up a PR if it is necessary.

**Comment by Gordon-Dry** [comment] 2021-12-27 14:58
This also seems to be the reason for the insanely low fps in R&D as soon as QuickSearch is used there.
No log spamming, just very slow responses on every aspect of the UI.

**Comment by jbayer-a3k** [comment] 2021-12-27 23:16
This is on my to-do list, it's incredibility annoying, as I'm sure you know

**Comment by jbayer-a3k** [comment] 2021-12-28 00:23
> This also seems to be the reason for the insanely low fps in R&D as soon as QuickSearch is used there. No log spamming, just very slow responses on every aspect of the UI.

Have you confirmed it's QuickSearch?  The code you highlighted doesn't really do that much.

also, the only slowdown I've seen is while entering a string in the quicksearch field, other than that, the editor seems ok

**Comment by Gordon-Dry** [comment] 2021-12-28 00:43
The OP was not me - and I have no issues in VAB (but a huge delay until thew search result appears), but the fps issue is in R&D.

**Comment by linuxgurugamer** [comment] 2021-12-29 13:37
The search issue in Editor has been fixed in the latest release.  I never experienced (and was unable to replicate) any issue in the R&D, but I implemented the same fix there, the problem was the same although the code was different.

**Closed by linuxgurugamer** 2021-12-29 13:37 UTC
